name: Release

on:
    push:
        branches:
            - main
            - alpha
            - beta
            - next

jobs:
    release:
        name: 🚀 Release
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Use Node.js v20.x
              uses: actions/setup-node@v1
              with:
                  node-version: 20.x

            - name: Install dependencies
              run: npm ci

            - name: Prepare svelte-kit
              run: npx svelte-kit sync

            - name: Run unit tests
              run: npm test
              env:
                  CI: true

            - name: Build and publish release
              run: npm run release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
